(* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*)

let rec fibsRec a b =
    if a + b < 4000000 then
        let current = a + b
        let rest = fibsRec b current
        current :: rest
    else 
        []

let fibs = 1::2::(fibsRec 1 2)|> List.toSeq |> Seq.filter (fun x -> x % 2 = 0) |> Seq.sum |> printfn "%d"
